services:
  - type: web
    name: global-expansion-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_PATH
        value: ./data/database.sqlite
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: ENABLE_EMAIL_NOTIFICATIONS
        value: false
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
